#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

#apt-get install -y debconf-utils

export DEBIAN_FRONTEND=noninteractive


apt-get  --allow-unauthenticated -y install mysql-client-5.6 mysql-server-5.6 percona-xtrabackup

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off
_EOF_

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]
!includedir /etc/mysql/conf.d/
_EOF_

cat >/lib/systemd/system/mysql.service <<_EOF_
# MySQL systemd service file

[Unit]
Description=MySQL Community Server
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
User=mysql
Group=mysql
PermissionsStartOnly=true
ExecStartPre=/usr/share/mysql/mysql-systemd-start pre
ExecStart=/usr/sbin/mysqld
ExecStartPost=/usr/share/mysql/mysql-systemd-start post
TimeoutSec=600
Restart=on-failure
RuntimeDirectory=mysqld
RuntimeDirectoryMode=755
_EOF_

cat >/usr/share/mysql/mysql-systemd-start <<'_EOF_'
#!/bin/bash
#
# Scripts to run by MySQL systemd service
#
# Needed argument: pre | post
#
# pre mode  :  try to perform sanity check for configuration, log, data
# post mode :  ping server until answer is received

sanity () {
  if [ ! -r /etc/mysql/my.cnf ]; then
    echo "MySQL configuration not found at /etc/mysql/my.cnf. Please create one."
    exit 1
  fi
}

pinger () {
  server_up=false
  for i in $(seq 1 30); do
    sleep 1
    if mysqladmin ping >/dev/null 2>&1; then
      server_up=true
      break
    fi
  done
  if [ ! $server_up ]; then
    echo "MySQL server not started"
    exit 1
  fi
}

case $1 in
  "pre")  sanity ;;
  "post") pinger ;;
esac
_EOF_

chmod 0755 /usr/share/mysql/mysql-systemd-start

rm -rf /etc/init/mysql.conf
rm -rf /etc/init.d/mysql
systemctl daemon-reload
systemctl enable mysql
