#!/bin/bash

# CONTEXT: GUEST during PRE-CONSTRUCTION as ROOT
# PURPOSE: Setup apt-repo list so that we can connect to Percona's repo

set -e
set -o xtrace

[ -n "${GUEST_USERNAME}" ] || die "GUEST_USERNAME needs to be set to the user for the guest image"
[ -n "${RELEASE}" ] || die "RELEASE must be set to either Precise or Quantal"

# Fetch the repository packages from Percona web
wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb

# Install the downloaded package with dpkg
dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb

# Fetch mysql repo - 5.7 specific
#wget https://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb

# Install the mysql repo - 5.7 specific
#dpkg -i mysql-apt-config_0.8.6-1_all.deb

# Needed for 5.6 mysql - Otherwise Xenial only comes with 5.7
add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

# Force an update
apt-get update

